# Generated by Django 4.2.2 on 2023-07-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('cname', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('established', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('cimage', models.ImageField(upload_to=None)),
                ('milage', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('description', models.TextField(default='car')),
            ],
        ),
    ]
